app/__init__.py
from flask import Flask
from flask_socketio import SocketIO
from .config import Config

socketio = SocketIO()
from .routes.socketio_events import *

def create_app():
    app = Flask(__name__)
    app.config.from_object(Config)
    
    from .routes.main_routes import main as main_blueprint
    from .routes.auth_routes import auth as auth_blueprint
    from .routes.download_routes import download as download_blueprint
    
    
    app.register_blueprint(main_blueprint)
    app.register_blueprint(auth_blueprint)
    app.register_blueprint(download_blueprint)
    
    socketio.init_app(app, cors_allowed_origins="*")
    
    return app

app/routes/auth_routes.py
from flask import Blueprint, redirect, request, session, render_template
from ..utils.spotify import create_spotify_oauth, get_token, gather_playlist_data
import spotipy

auth = Blueprint('auth', __name__)

@auth.route('/login')
def login():
    """Route that sends user to Spotify auth webpage
    
    Gathers URL from Spotify Oauth object and redirects user

    Returns:
        REDIRCT: Spotify app authorization URL
    """
    
    sp_oauth = create_spotify_oauth()
    auth_url = sp_oauth.get_authorize_url()
    
    return redirect(auth_url)

@auth.route('/callback')
def callback():
    """Route from successful Spotify login

    Returns:
        REDIRECT: /selectPlaylist route
    """
    
    sp_auth = create_spotify_oauth()
    session.clear()
    
    #Sets token info for user session
    code = request.args.get('code')
    token_info = sp_auth.get_access_token(code)
    session["token_info"] = token_info
    
    return redirect('/selectPlaylist')

@auth.route('/selectPlaylist')
def selectPlaylist():
    """Route that allows user to select one of their spotify playlists to download

    Returns:
        HTML: 'selectplaylist.html'
        playlists: list of playlist names to be displayed
    """
    
    
    #Validates user token
    try:
        token_info = get_token()
    except:
        return redirect('/')
    
    sp = spotipy.Spotify(auth=token_info['access_token'])
    playlist_data = sp.current_user_playlists()["items"]
    
    #Gets and stores playlist data in session 
    playlist_names, playlist_links = gather_playlist_data(playlist_data)
    session['PLAYLIST_DATA'] = dict(zip(playlist_names, playlist_links))
    
    return render_template('selectplaylist.html', playlists=playlist_names)

app/routes/download_routes.py
from flask import Blueprint, request, render_template, send_file, redirect, session, current_app
import os
from ..utils.download import download_tracks
from ..utils.spotify import get_token
from .. import socketio

download = Blueprint('download', __name__)

@download.route('/download', methods=['POST'])
def download_route():
    """Route for downloading playlist tracks
    
    Gathers required data such which is then sent to socketio 
    to download tracks in the background
    
    POST: handles playlist selection data

    Returns:
        HTML: download.html template
    """
    
    
    #Validates user token and playlist
    try:
        playlist_name = request.form.get("playlist")
        token_info = get_token()    
    except:
        return redirect('/')
    
    #Gathers required data (needs app context)
    base_url = request.host_url.rstrip('/')
    root_path = current_app.root_path
    playlist_data = session.get('PLAYLIST_DATA', {})
    playlist_link = playlist_data.get(playlist_name).split('/')[-2]
    
    socketio.start_background_task(download_tracks, playlist_link, playlist_name, token_info, base_url, root_path)
    
    return render_template("download.html")

@download.route('/playlistdownload/<playlist_file>')
def playlist_download(playlist_file: str):
    """Route handling the template of the file download

    Args:
        playlist_file (str): path to zip file of playlist

    Returns:
        HTML: playlistdownload.html template
        HTML: 404 error 
    """
    file_path = current_app.root_path + '/playlist/' + playlist_file
    
    #Check if path exists if not return error
    if os.path.exists(file_path):
        return render_template('playlistdownload.html', playlist_file=playlist_file)
    else:
        return "File not found", 404

@download.route('/sendfile/<path:file_path>')
def send_playlist(file_path: str):
    """Sends file to user for download

    Sends already validated file path to user when clicked on 
    in the playlistdownload.html
    
    Args:
        filePath (str): path to file

    Returns:
        file: downloaded file
    """
    return send_file(file_path)

app/routes/main_routes.py
from flask import Blueprint, render_template

main = Blueprint('main', __name__)

@main.route('/')
def index():
    """Main route

    Returns:
        HTML: index template
    """
    return render_template('index.html')

app/routes/socketio_events.py
from .. import socketio
from ..utils.helpers import delete_old_files
import os

@socketio.on('connect', namespace='/download')
def handle_connect():
    """Handles connection to socketIO on /download
    """
    
    print("Client connected")
    socketio.emit('message', {'data': 'Connected to server'}, namespace='/')

@socketio.on('disconnect', namespace='/download')
def handle_disconnect():
    """Handles discnnection to socketIO on /download
    
    Function also causes the playlist folder to be cleared, 
    deleting any files that are older than a day
    """
    
    print("Client disconnected")
    
    # Clears old playlists 
    playlist_folder_path = os.path.join(os.getcwd(), 'app', 'playlist')
    delete_old_files(playlist_folder_path)

app/templates/download.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    <title>Download Progress</title>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/4.0.0/socket.io.js"></script>
    <script src="{{ url_for('static', filename='js/download.js') }}"></script>
</head>
<body>
    <h1>Downloading Playlist's Tracks...</h1>
    
    <div id="current-track-download">
        <span>Currently downloading... </span>
        <span id="current-track-download-text"></span>
    </div>

    <div id="track-progress-container">
        <progress id="track-progress-bar" value="0" max="100"></progress>
        <span id="track-progress-text">0%</span>
        <span id="track-speed-text"></span>
    </div>

    <div id="track-number-container">
        <span id="tracks-completed-text">0</span>
        <span>/</span>
        <span id="total-tracks-text">0</span>
    </div>
</body>
</html>

app/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Spotify to MP3 Converter</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
</head>
<body>
    <h1>Spotify to MP3 Converter</h1>
    <button onclick="window.location.href='/login'">Login to Spotify</button>
</body>
</html>

app/templates/playlistdownload.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    <title>Download Playlist</title>
</head>
<body>
    <h1>Click Button Below to Download Playlist</h1>
    <a href="{{ url_for('download.send_playlist', file_path='playlist/' + playlist_file) }}">Download Playlist</a>
</body>
</html>

app/templates/selectplaylist.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Select Playlist</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
</head>
<body>
    <h1>Select an Playlist to Start Downloading</h1>
    <form action="/download" method="post">
        <select name="playlist">
            {% for playlist in playlists %}
                <option value="{{ playlist }}">{{ playlist }}</option>
            {% endfor %}
        </select>
        <button type="submit">Begin Download</button>
    </form>
</body>
</html>